/* ============================================================
   世界考古发现档案馆 — 考古发现数据库
   包含全球重要考古发现、遗址、文物详细数据
   ============================================================ */
'use strict';

// ==================== Archaeological Discoveries Database ====================
const DISCOVERY_DATABASE = [
  {
    id: 'tutankhamun_tomb',
    name: '图坦卡蒙陵墓',
    nameEn: 'Tomb of Tutankhamun',
    location: '埃及卢克索帝王谷',
    country: '埃及',
    region: 'egypt',
    year: 1922,
    era: '新王国时期',
    eraYear: '约公元前1323年',
    discoverer: '霍华德·卡特 (Howard Carter)',
    category: '陵墓',
    material: ['金', '木', '石', '宝石'],
    description: '1922年11月4日，英国考古学家霍华德·卡特在埃及帝王谷发现了几乎未被盗掘的图坦卡蒙法老陵墓（KV62号墓）。这是埃及考古史上最伟大的发现之一，墓中出土了超过5000件精美文物。',
    detailedAnalysis: '图坦卡蒙是古埃及第十八王朝的法老，约9岁即位，19岁去世。他的陵墓之所以成为考古史上传奇，正是因为其保存之完好令人惊叹——三千多年来几乎未被盗墓者洗劫。陵墓由四个墓室组成：前厅、附厅、棺椁室和宝库。最令人震撼的是法老的黄金面具，由11公斤纯金打造，镶嵌青金石、绿松石等宝石，工艺精湛绝伦。墓中还发现了黄金王座、战车、武器、家具、衣物、食品、美酒等随葬品，为我们了解古埃及王室生活提供了无与伦比的窗口。卡特花费了近10年时间才完成全部文物的清理和记录工作。',
    significance: '20世纪最伟大的考古发现之一，揭示了古埃及第十八王朝的辉煌文明',
    themes: ['古埃及', '法老', '墓葬考古', '黄金文物'],
    famousQuotes: ['"是的，我看到奇妙的东西了！" — 霍华德·卡特回答卡那封勋爵"你看到什么了吗？"'],
    imageClass: 'artifact-deathmask',
    icon: '👑',
    tags: ['埃及', '陵墓', '黄金', '法老', '1922年'],
    featured: true,
    pageUrl: 'pages/egyptian_civilization.html',
    excavationStatus: '已完成发掘',
    currentLocation: '埃及卢克索帝王谷（原位）/ 开罗埃及博物馆',
    conservationStatus: 'excellent',
    impactLevel: 5
  },
  {
    id: 'terracotta_army',
    name: '秦始皇兵马俑',
    nameEn: 'Terracotta Army',
    location: '中国陕西省西安市临潼区',
    country: '中国',
    region: 'china',
    year: 1974,
    era: '秦代',
    eraYear: '约公元前210年',
    discoverer: '当地农民打井时发现',
    category: '墓葬陪葬',
    material: ['陶', '青铜', '木'],
    description: '1974年3月，陕西临潼农民在打井时意外发现了兵马俑碎片，由此揭开了世界第八大奇迹的面纱。三个俑坑共出土约8000件陶俑、陶马和战车。',
    detailedAnalysis: '兵马俑坑位于秦始皇陵以东1.5公里处，是秦始皇陵的陪葬坑。目前发现的三个俑坑呈品字形排列：一号坑最大，东西长230米、南北宽62米，总面积14260平方米，内有约6000件陶俑；二号坑面积6000平方米，包含骑兵、战车和步兵混合编队；三号坑面积520平方米，被认为是军队的指挥部。每件陶俑都独一无二——不同的面部表情、发型、服饰和姿势，展现出秦代雕塑艺术的高度写实性。陶俑原本施有彩绘，但由于出土后氧化，大部分颜色已经脱落。青铜战车和青铜兵器的发现，更印证了秦代冶金技术的高超水平。',
    significance: '世界第八大奇迹，展现了秦代军事力量和雕塑艺术的巅峰',
    themes: ['秦始皇', '陪葬', '陶俑', '军事考古'],
    famousQuotes: ['"这是世界的第八大奇迹" — 希拉克 (法国前总统)'],
    imageClass: 'artifact-warrior',
    icon: '🗿',
    tags: ['中国', '兵马俑', '秦代', '陶俑', '1974年'],
    featured: true,
    pageUrl: 'pages/chinese_archaeology.html',
    excavationStatus: '持续发掘中',
    currentLocation: '中国西安秦始皇兵马俑博物馆',
    conservationStatus: 'good',
    impactLevel: 5
  },
  {
    id: 'rosetta_stone',
    name: '罗塞塔石碑',
    nameEn: 'Rosetta Stone',
    location: '埃及罗塞塔（拉希德）',
    country: '埃及',
    region: 'egypt',
    year: 1799,
    era: '托勒密时期',
    eraYear: '公元前196年',
    discoverer: '皮埃尔-弗朗索瓦·布沙尔 (法军士兵)',
    category: '石碑',
    material: ['花岗闪长岩'],
    description: '1799年法军在埃及罗塞塔修筑防御工事时发现。石碑上刻有同一段文字的三种不同版本：古埃及象形文字、埃及草书体和古希腊文，成为解读象形文字的关键。',
    detailedAnalysis: '罗塞塔石碑高114.4厘米、宽72.3厘米、厚27.9厘米，重约760公斤。石碑上的文字是托勒密五世的一道法令，颁布于公元前196年3月27日。石碑的发现开启了埃及学的科学研究时代。英国物理学家托马斯·杨首先识别出部分象形文字的语音价值，而法国语言学家商博良在1822年最终完成了象形文字的破译工作。通过对比三种文字，商博良确认古埃及象形文字是一种兼具表意和表音功能的复杂书写系统。从此，古埃及数千年的文字记录不再神秘，埃及学作为一门现代学科正式诞生。',
    significance: '解读古埃及象形文字的关键之钥，开启埃及学研究的大门',
    themes: ['文字破译', '语言学', '石碑', '埃及学'],
    famousQuotes: ['"我终于破解了！" — 商博良'],
    imageClass: 'artifact-stone',
    icon: '📜',
    tags: ['埃及', '石碑', '象形文字', '语言学', '1799年'],
    featured: true,
    pageUrl: 'pages/egyptian_civilization.html',
    excavationStatus: '已完整保存',
    currentLocation: '英国伦敦大英博物馆',
    conservationStatus: 'excellent',
    impactLevel: 5
  },
  {
    id: 'sanzigdui',
    name: '三星堆遗址',
    nameEn: 'Sanxingdui Site',
    location: '中国四川省广汉市',
    country: '中国',
    region: 'china',
    year: 1929,
    era: '商代晚期',
    eraYear: '约公元前1200年',
    discoverer: '燕道诚（首次发现）',
    category: '祭祀遗址',
    material: ['青铜', '金', '玉', '象牙'],
    description: '三星堆遗址的发现彻底改变了人们对古蜀文明的认知。1986年两个祭祀坑的发掘震惊了世界，出土了青铜大立人像、青铜神树、金杖、纵目面具等旷世奇珍。',
    detailedAnalysis: '三星堆遗址总面积约12平方公里，是古蜀国最重要的都城遗址之一。2020年以来的新一轮发掘更是在六个祭祀坑中出土了超过17000件文物，其中包括完整的黄金面具、前所未见的青铜祭坛、丝绸残留物等。青铜神树高达3.96米，是中国目前发现最大的青铜器之一，其工艺复杂度令人叹为观止。纵目面具宽达1.38米，眼球突出，造型奇特，引发了关于古蜀人是否与外星文明有联系的无尽遐想（实际更多反映的是蜀人始祖蚕丛"纵目"的传说）。金杖上刻画的人头、鸟、鱼图案被认为是古蜀王权的象征。',
    significance: '揭示古蜀文明高度发达的青铜文明和独特的宗教艺术体系',
    themes: ['古蜀文明', '青铜器', '祭祀', '商代'],
    famousQuotes: ['"沉睡三千年，一醒惊天下"'],
    imageClass: 'artifact-mask',
    icon: '🎭',
    tags: ['中国', '青铜器', '古蜀', '商代', '祭祀'],
    featured: true,
    pageUrl: 'pages/chinese_archaeology.html',
    excavationStatus: '持续发掘中（2020年启动新一轮）',
    currentLocation: '中国四川广汉三星堆博物馆',
    conservationStatus: 'good',
    impactLevel: 5
  },
  {
    id: 'pompeii',
    name: '庞贝古城',
    nameEn: 'Pompeii',
    location: '意大利坎帕尼亚那不勒斯湾',
    country: '意大利',
    region: 'greek-roman',
    year: 1748,
    era: '罗马帝国时期',
    eraYear: '公元79年',
    discoverer: '多梅尼科·丰塔纳（1599年首次发现）/ 1748年正式发掘',
    category: '古城遗址',
    material: ['石', '壁画', '马赛克', '青铜'],
    description: '公元79年维苏威火山大爆发，将繁荣的罗马城市庞贝埋在6米厚的火山灰下。千年之后，这座被时间冻结的城市以惊人的完整性重见天日。',
    detailedAnalysis: '庞贝古城的考古发掘是考古学史上规模最大、持续时间最长的项目之一。火山灰完美地保存了城市的每一个细节：街道上的车辙、面包店里的碳化面包、墙壁上的政治标语和涂鸦、奢华的壁画和马赛克地板。考古学家朱塞佩·菲奥雷利在1863年发明了石膏灌注法——向火山灰中的空腔注入石膏，复原了遇难者最后的姿态。庞贝为我们提供了一幅完整的公元1世纪罗马城市生活的横截面画卷，涵盖城市规划、建筑技术、日常生活、经济贸易、宗教信仰等各个方面。至今，庞贝仍有约三分之一未发掘。',
    significance: '最完整保存的古罗马城市，提供了古代城市生活的全方位信息',
    themes: ['古罗马', '火山', '城市考古', '壁画'],
    famousQuotes: ['"庞贝是时间赠予人类最珍贵的礼物"'],
    imageClass: 'artifact-ruins',
    icon: '🏛️',
    tags: ['意大利', '罗马', '火山', '城市', '壁画'],
    featured: true,
    pageUrl: 'pages/greek_roman.html',
    excavationStatus: '持续发掘中（至今三分之一未发掘）',
    currentLocation: '意大利庞贝考古遗址公园',
    conservationStatus: 'fair',
    impactLevel: 5
  },
  {
    id: 'machu_picchu',
    name: '马丘比丘',
    nameEn: 'Machu Picchu',
    location: '秘鲁库斯科西北75公里',
    country: '秘鲁',
    region: 'americas',
    year: 1911,
    era: '印加帝国时期',
    eraYear: '约公元1450年',
    discoverer: '海勒姆·宾厄姆 (Hiram Bingham)',
    category: '城市遗址',
    material: ['花岗岩'],
    description: '马丘比丘是印加帝国最著名的遗址，建在海拔2430米的山脊上，被誉为"天空之城"。1911年美国探险家海勒姆·宾厄姆在当地原住民的指引下重新发现了这座被丛林掩盖的古城。',
    detailedAnalysis: '马丘比丘占地约13平方公里，包括约200座石结构建筑，分为农业区、居住区、宗教区和皇家区。最令人惊叹的是其石材加工技术——巨大的花岗岩石块被切割得如此精确，无需灰浆即可紧密拼接，即使刀片也无法插入石缝之间。这种建筑技术称为"阿什拉尔"（ashlar），具有极佳的抗震性能。遗址中最重要的建筑包括太阳神庙（Intihuatana，意为"拴日石"）、三窗庙和主庙。马丘比丘的水利系统同样令人印象深刻，包括阶梯式喷泉和复杂的排水渠道。尽管西班牙征服者从未发现此地，该城在印加帝国灭亡后被遗弃，原因至今仍是谜。',
    significance: '印加文明的巅峰之作，新世界最壮观的考古遗址之一',
    themes: ['印加文明', '石建筑', '山地城市', '天文'],
    famousQuotes: ['"马丘比丘是人类建筑与自然完美结合的典范"'],
    imageClass: 'artifact-temple',
    icon: '🏔️',
    tags: ['秘鲁', '印加', '山城', '石建筑', '1911年'],
    featured: true,
    pageUrl: 'pages/americas_civilization.html',
    excavationStatus: '部分发掘完成',
    currentLocation: '秘鲁库斯科马丘比丘历史保护区',
    conservationStatus: 'good',
    impactLevel: 5
  },
  {
    id: 'dead_sea_scrolls',
    name: '死海古卷',
    nameEn: 'Dead Sea Scrolls',
    location: '死海西北岸库姆兰洞穴',
    country: '以色列/巴勒斯坦',
    region: 'mesopotamia',
    year: 1947,
    era: '第二圣殿时期',
    eraYear: '约公元前250年-公元68年',
    discoverer: '贝都因牧羊少年',
    category: '文献',
    material: ['羊皮纸', '莎草纸', '铜'],
    description: '1947年，一名贝都因牧羊少年在寻找丢失的羊时，向一个洞穴投掷石块，听到了陶罐破碎的声音——这一掷开启了20世纪最伟大的文献考古发现。死海古卷包含约900卷手稿，是最早的希伯来圣经抄本。',
    detailedAnalysis: '死海古卷在11个洞穴中被发现，包括《希伯来圣经》除《以斯帖记》外的所有经卷、次经、伪经以及库姆兰社团的规章文献。其中《以赛亚书》全卷抄本是迄今发现最完整的圣经古抄本，比之前最早的马索拉抄本早了一千年。古卷的书写材料大部分为羊皮纸，少量为莎草纸，还有独特的铜制卷轴。碳十四测年证实这些古卷的年代在公元前250年至公元68年之间。死海古卷彻底改变了人们对希伯来圣经文本传播史和早期犹太教、基督教背景的认知。',
    significance: '现存最古老的《希伯来圣经》抄本，对犹太教和早期基督教研究具有革命性意义',
    themes: ['文献', '宗教', '圣经', '手稿'],
    famousQuotes: ['"这是人类精神遗产中最伟大的考古发现" — 威廉·奥尔布赖特'],
    imageClass: 'artifact-scroll',
    icon: '📜',
    tags: ['以色列', '文献', '圣经', '羊皮卷', '1947年'],
    featured: false,
    pageUrl: 'pages/mesopotamia.html',
    excavationStatus: '已完成发掘',
    currentLocation: '耶路撒冷以色列博物馆',
    conservationStatus: 'fair',
    impactLevel: 5
  },
  {
    id: 'gobekli_tepe',
    name: '哥贝克力石阵',
    nameEn: 'Göbekli Tepe',
    location: '土耳其东南部尚勒乌尔法省',
    country: '土耳其',
    region: 'mesopotamia',
    year: 1963,
    era: '新石器时代',
    eraYear: '约公元前9500年',
    discoverer: '克劳斯·施密特 (Klaus Schmidt)',
    category: '祭祀遗址',
    material: ['石灰岩'],
    description: '哥贝克力石阵是迄今为止发现的最古老的大型宗教建筑群，其年代距今约11500年，比金字塔还要早7000年。遗址中巨大的T形石柱上雕刻着精美的动物浮雕。',
    detailedAnalysis: '哥贝克力石阵占地约9公顷，由至少20个圆形或椭圆形石阵组成，每个石阵中心竖立着两块巨大的T形石柱，周围环绕着稍小的石柱。最大的石柱高5.5米、重达16吨。石柱上浮雕包括狐狸、狮子、野猪、蛇、蝎子、鸟类等动物形象以及抽象符号。这些石阵的建造需要数百人协同工作，表明在农业革命之前，人类已经能够组织起大规模的社会协作——这一发现颠覆了"先有农业、后有文明"的传统认知。德国考古学家克劳斯·施密特认为，哥贝克力石阵是人类最早的"大教堂"，是狩猎采集者聚集举行宗教仪式的中心。遗址仅发掘了约5%，尚有大量未知等待揭示。',
    significance: '颠覆了农业革命与文明起源的传统理论，是世界上已知最早的大型祭祀建筑群',
    themes: ['史前', '新石器', '宗教', '建筑起源'],
    famousQuotes: ['"这是人类信仰诞生的地方" — 克劳斯·施密特'],
    imageClass: 'artifact-megalith',
    icon: '🗿',
    tags: ['土耳其', '新石器', '巨石', '宗教', '史前'],
    featured: true,
    pageUrl: 'pages/mesopotamia.html',
    excavationStatus: '持续发掘中（仅发掘约5%）',
    currentLocation: '土耳其尚勒乌尔法哥贝克力石阵考古遗址',
    conservationStatus: 'fair',
    impactLevel: 5
  },
  {
    id: 'terracotta_warriors_tomb',
    name: '秦始皇陵',
    nameEn: 'Mausoleum of the First Qin Emperor',
    location: '中国陕西省西安市临潼区',
    country: '中国',
    region: 'china',
    year: 1974,
    era: '秦代',
    eraYear: '约公元前246-208年',
    discoverer: '已知位置，兵马俑的发现属偶然',
    category: '陵墓',
    material: ['土', '石', '青铜', '水银'],
    description: '秦始皇陵是中国历史上规模最宏大的帝王陵墓，据《史记》记载，陵墓内"以水银为百川江河大海，机相灌输，上具天文，下具地理"。目前陵墓核心区域尚未发掘。',
    detailedAnalysis: '秦始皇陵的考古工作已经持续了数十年，但出于文物保护考虑，地宫核心区域至今仍未发掘。遥感探测和钻探取样表明，陵墓封土下的地宫规模巨大，汞含量异常高（印证了《史记》关于水银江河的记载），墓道和墓室结构复杂。已发掘的陪葬坑包括兵马俑坑、铜车马坑、珍禽异兽坑、石甲胄坑等180余座。最新研究认为，秦始皇陵的设计理念可能是对秦帝国版图的微缩再现。',
    significance: '中国历史上规模最宏大的帝王陵墓，世界文化遗产',
    themes: ['秦始皇', '帝陵', '中国考古', '墓葬'],
    famousQuotes: ['"秦王扫六合，虎视何雄哉" — 李白'],
    imageClass: 'artifact-mausoleum',
    icon: '🏯',
    tags: ['中国', '秦始皇', '帝陵', '陪葬', '1974年'],
    featured: false,
    pageUrl: 'pages/chinese_archaeology.html',
    excavationStatus: '陪葬坑发掘中，地宫未开启',
    currentLocation: '中国西安秦始皇陵遗址公园',
    conservationStatus: 'good',
    impactLevel: 5
  },
  {
    id: 'troy',
    name: '特洛伊古城',
    nameEn: 'Ancient Troy',
    location: '土耳其恰纳卡莱希沙利克',
    country: '土耳其',
    region: 'greek-roman',
    year: 1870,
    era: '青铜时代至罗马时期',
    eraYear: '约公元前3000年-公元500年',
    discoverer: '海因里希·施里曼 (Heinrich Schliemann)',
    category: '古城遗址',
    material: ['石', '青铜', '金'],
    description: '特洛伊是荷马史诗《伊利亚特》中特洛伊战争的舞台。1870年，德国考古学家施里曼坚信特洛伊真实存在，最终在土耳其希沙利克发现了这座城邦遗址，并出土了所谓的"普里阿摩斯的宝藏"。',
    detailedAnalysis: '特洛伊遗址实际上包含9个主要层位，从青铜时代早期（约公元前3000年）一直延续到罗马时期。施里曼最初错误地将特洛伊II期（约公元前2500年）认定为荷马的特洛伊，后来才确认特洛伊VIIa期（约公元前1250年）才是与特洛伊战争时期最契合的城邦。在特洛伊VIIa层中，考古学家发现了战争和火灾的痕迹，以及将大型储粮罐埋入地下的现象，表明城市曾经历围城之困。特洛伊的发掘是考古学史上最具传奇色彩的故事之一，也开启了用考古证据验证文献记载的先河。',
    significance: '证实荷马史诗历史背景的重要发现，考古学与文学交汇的典范',
    themes: ['青铜时代', '荷马史诗', '城邦', '战争'],
    famousQuotes: ['"我找到了普里阿摩斯的宝藏！" — 施里曼'],
    imageClass: 'artifact-city',
    icon: '🐴',
    tags: ['土耳其', '特洛伊', '荷马', '青铜时代', '1870年'],
    featured: false,
    pageUrl: 'pages/greek_roman.html',
    excavationStatus: '多阶段发掘已完成',
    currentLocation: '土耳其特洛伊考古遗址',
    conservationStatus: 'fair',
    impactLevel: 4
  },
  {
    id: 'nazca_lines',
    name: '纳斯卡线条',
    nameEn: 'Nazca Lines',
    location: '秘鲁纳斯卡沙漠',
    country: '秘鲁',
    region: 'americas',
    year: 1927,
    era: '纳斯卡文化时期',
    eraYear: '约公元前500年-公元500年',
    discoverer: '托里维奥·梅希亚·谢斯佩（首次科学调查）/ 保罗·科索克（空中发现）',
    category: '地面图画',
    material: ['地面刻画'],
    description: '纳斯卡线条是南美洲最神秘的考古遗址之一，在约500平方公里的沙漠上刻画着数百幅巨大的动物、植物和几何图形，只有从空中才能完整观测。',
    detailedAnalysis: '纳斯卡线条包括超过800条直线、300多个几何图形和约70个动植物图案（蜂鸟、蜘蛛、猴子、鲸鱼、花等）。最大的图案长达370米。这些线条是通过移除沙漠表面氧化的深色砾石，露出下面较浅的土壤而形成的。干燥、无风的气候使得这些2000年前的线条得以保存至今。2022年，日本山形大学利用人工智能和无人机技术又在纳斯卡地区新发现了168幅地画。关于线条的用途，主流假说认为与天文观测和宗教仪式有关，但也有各种奇思妙想的解释。',
    significance: '世界上最神秘的地面图画群，古代安第斯文明的杰出创造',
    themes: ['地理标志', '纳斯卡', '天文', '宗教'],
    famousQuotes: ['"纳斯卡是写在大地上的天书"'],
    imageClass: 'artifact-lines',
    icon: '🕊️',
    tags: ['秘鲁', '纳斯卡', '地面画', '神秘', '1927年'],
    featured: true,
    pageUrl: 'pages/americas_civilization.html',
    excavationStatus: '非发掘类遗址，持续测绘中',
    currentLocation: '秘鲁纳斯卡和帕尔帕省',
    conservationStatus: 'fair',
    impactLevel: 4
  },
  {
    id: 'antikythera',
    name: '安提基特拉机械',
    nameEn: 'Antikythera Mechanism',
    location: '希腊安提基特拉岛海域沉船',
    country: '希腊',
    region: 'greek-roman',
    year: 1901,
    era: '希腊化时期',
    eraYear: '约公元前150-100年',
    discoverer: '海绵潜水员',
    category: '科技文物',
    material: ['青铜'],
    description: '安提基特拉机械是世界上最古老的模拟计算机，1901年从爱琴海一艘古代沉船中打捞出水。这台由至少30个精密青铜齿轮组成的装置能计算天体位置和预测日食月食。',
    detailedAnalysis: '安提基特拉机械由至少30个齿轮组成（可能多达37个），被封装在一个约34×18×9厘米的木盒中。通过X射线断层扫描和三维重建，研究人员发现这个装置可以预测太阳、月亮和已知五大行星的位置，计算日食月食的时间，甚至可以追踪奥林匹克运动会的四年周期。齿轮的精密程度令人震惊——其工艺水平直到14世纪的天文钟才再次出现。2012年的研究还揭示了齿轮上的铭文，说明这是一个教学工具而非唯一的计算器，暗示可能存在更早的原型。它的发现彻底改写了技术史。',
    significance: '世界上最古老的模拟计算机，证明古希腊科技水平远超此前认知',
    themes: ['古希腊', '科技', '天文', '航海'],
    famousQuotes: ['"如果古希腊人能造出这个，历史将会完全不同" — 德里克·德索拉·普莱斯'],
    imageClass: 'artifact-gear',
    icon: '⚙️',
    tags: ['希腊', '科技', '天文', '青铜', '1901年'],
    featured: false,
    pageUrl: 'pages/greek_roman.html',
    excavationStatus: '已完成打捞和修复',
    currentLocation: '希腊雅典国家考古博物馆',
    conservationStatus: 'poor',
    impactLevel: 5
  },
  {
    id: 'mohenjo_daro',
    name: '摩亨佐-达罗',
    nameEn: 'Mohenjo-daro',
    location: '巴基斯坦信德省拉尔卡纳',
    country: '巴基斯坦',
    region: 'mesopotamia',
    year: 1922,
    era: '印度河文明',
    eraYear: '约公元前2500-1900年',
    discoverer: 'R·D·班纳吉 (R. D. Banerji)',
    category: '城市遗址',
    material: ['砖', '石', '青铜', '陶'],
    description: '摩亨佐-达罗是印度河文明最大的城市遗址之一，其先进的城市规划令人惊叹——棋盘式街道布局、完整的排水系统、公共浴池和粮仓都表明这是一个高度组织化的社会。',
    detailedAnalysis: '摩亨佐-达罗占地约250公顷，鼎盛时期人口约4万。城市分为"城堡区"（统治和宗教中心）和"下城区"（居民区）。最著名的建筑是"大浴池"，长12米、宽7米、深2.4米，由砖砌成并用沥青防水，被认为是宗教净化的场所。城市的排水系统发达程度在古代世界中无与伦比——几乎每栋房屋都有私人浴室和厕所，废水通过陶制管道排入主街道下方的砖砌下水道。然而，印度河文明的文字至今未能破译，这个伟大文明的历史仍然笼罩在谜雾之中。',
    significance: '印度河文明最杰出的城市遗址，展现了公元前三千纪高度发达的城市文明',
    themes: ['印度河文明', '城市规划', '青铜时代', '排水系统'],
    famousQuotes: ['"一个没有宫殿、没有庙宇、没有陵墓的平等社会？"'],
    imageClass: 'artifact-city',
    icon: '🏙️',
    tags: ['巴基斯坦', '印度河', '青铜时代', '城市', '1922年'],
    featured: false,
    pageUrl: 'pages/mesopotamia.html',
    excavationStatus: '部分发掘',
    currentLocation: '巴基斯坦信德省摩亨佐-达罗考古遗址',
    conservationStatus: 'poor',
    impactLevel: 4
  },
  {
    id: 'sutton_hoo',
    name: '萨顿胡船葬',
    nameEn: 'Sutton Hoo',
    location: '英格兰萨福克郡',
    country: '英国',
    region: 'greek-roman',
    year: 1939,
    era: '盎格鲁-撒克逊时期',
    eraYear: '约公元625年',
    discoverer: '巴兹尔·布朗 (Basil Brown)',
    category: '墓葬',
    material: ['金', '银', '铁', '宝石', '木'],
    description: '萨顿胡船葬是英国最伟大的考古发现之一。一艘27米长的橡木船作为一位盎格鲁-撒克逊国王的陵墓，船内随葬品包括著名的萨顿胡头盔、金带扣、钱币和来自拜占庭的银器等。',
    detailedAnalysis: '萨顿胡船葬遗址共有约20个墓葬墩。最大的1号墩包含一艘27米长的海葬船（船木已腐朽但留下了完美的印痕）。墓室中的随葬品令人叹为观止：萨顿胡头盔是盎格鲁-撒克逊艺术最杰出的代表作之一，由铁和铜合金制成，面罩镶嵌石榴石，眉毛末端雕刻为野猪头形；金带扣重达412克，装饰着复杂的交织动物纹样；来自拜占庭帝国的银盘、来自斯堪的纳维亚的盾牌、来自法国的金币——这些都暗示着盎格鲁-撒克逊英格兰与欧亚大陆广泛的贸易和文化联系。学界普遍认为墓主可能是东盎格利亚国王雷德沃尔德。',
    significance: '英国最重要的考古发现之一，揭示了早期盎格鲁-撒克逊王国的繁荣',
    themes: ['中世纪', '船葬', '英国', '王国'],
    famousQuotes: ['"这是英国的特洛伊"'],
    imageClass: 'artifact-helmet',
    icon: '⛵',
    tags: ['英国', '船葬', '盎格鲁-撒克逊', '金器', '1939年'],
    featured: false,
    pageUrl: 'pages/greek_roman.html',
    excavationStatus: '已完成发掘',
    currentLocation: '英国伦敦大英博物馆',
    conservationStatus: 'excellent',
    impactLevel: 4
  },
  {
    id: 'oracle_bones',
    name: '殷墟甲骨文',
    nameEn: 'Oracle Bones from Yinxu',
    location: '中国河南省安阳市',
    country: '中国',
    region: 'china',
    year: 1899,
    era: '商代',
    eraYear: '约公元前1250-1046年',
    discoverer: '王懿荣（首次识别为古文字）',
    category: '文献',
    material: ['龟甲', '牛骨'],
    description: '甲骨文的发现是将中国信史向前推进了数百年的关键事件。1899年，国子监祭酒王懿荣在中药"龙骨"上发现了刻划符号，确认这是商代的古老文字。后来确定出土地为安阳殷墟。',
    detailedAnalysis: '殷墟甲骨文的出土数量惊人——迄今已发现约15万片，记录了商代晚期273年的历史。这些甲骨文主要是商王占卜的记录，内容涵盖祭祀、战争、天气、农业、疾病、生育等各个方面。通过对甲骨文的研究，学者们不仅确认了司马迁《史记·殷本纪》中商王世系的真实性，更重构了商代的政治制度、社会结构、宗教观念和经济形态。甲骨文是汉字最早的成熟形态，约有5000个单字，其中约1500个已被释读。2017年，甲骨文入选联合国教科文组织《世界记忆名录》。',
    significance: '中国最早成系统的文字记录，将中国信史推进至商代',
    themes: ['文字', '商代', '占卜', '中国考古'],
    famousQuotes: ['"一片甲骨惊天下"'],
    imageClass: 'artifact-bone',
    icon: '🐢',
    tags: ['中国', '甲骨文', '商代', '文字', '1899年'],
    featured: false,
    pageUrl: 'pages/chinese_archaeology.html',
    excavationStatus: '持续整理中',
    currentLocation: '中国国家博物馆、故宫博物院、安阳殷墟博物馆等',
    conservationStatus: 'fair',
    impactLevel: 5
  },
  {
    id: 'pyramids_giza',
    name: '吉萨金字塔群',
    nameEn: 'Giza Pyramid Complex',
    location: '埃及开罗郊区吉萨高原',
    country: '埃及',
    region: 'egypt',
    year: 0,
    era: '古王国时期',
    eraYear: '约公元前2580-2560年',
    discoverer: '从未真正"失传"',
    category: '陵墓',
    material: ['石灰岩', '花岗岩'],
    description: '吉萨金字塔群是古代世界七大奇迹中唯一保存至今的。胡夫金字塔原高146.6米，由约230万块巨石砌成，每块平均重2.5吨，最大达80吨。其建造精度和规模至今令人惊叹。',
    detailedAnalysis: '吉萨金字塔群包括胡夫、哈夫拉和孟卡拉三座大金字塔，以及狮身人面像和众多小金字塔、神庙和贵族墓。胡夫金字塔底边各长230米，四边方向与东南西北几乎完全对齐，误差不超过0.05度。2017年，μ子成像技术在胡夫金字塔内部发现了一个巨大的未知空间（"大空洞"），长约30米，至今尚未开启。金字塔的建造技术仍是争论焦点，但越来越多的考古证据支持埃及工人（而非奴隶）利用斜坡系统、滑轮和杠杆，以高度组织化方式完成这一奇迹的假说。',
    significance: '古埃及文明的象征，古代世界七大奇迹中唯一幸存者',
    themes: ['金字塔', '古埃及', '建筑', '工程'],
    famousQuotes: ['"人类畏惧时间，而时间畏惧金字塔"'],
    imageClass: 'artifact-pyramid',
    icon: '🔺',
    tags: ['埃及', '金字塔', '古王国', '建筑', '世界奇迹'],
    featured: false,
    pageUrl: 'pages/egyptian_civilization.html',
    excavationStatus: '测绘与研究持续中',
    currentLocation: '埃及吉萨省吉萨高原',
    conservationStatus: 'good',
    impactLevel: 5
  },
  {
    id: 'chichen_itza',
    name: '奇琴伊察',
    nameEn: 'Chichén Itzá',
    location: '墨西哥尤卡坦半岛',
    country: '墨西哥',
    region: 'americas',
    year: 1840,
    era: '玛雅后古典时期',
    eraYear: '约公元750-1200年',
    discoverer: '约翰·劳埃德·斯蒂芬斯和弗雷德里克·卡瑟伍德',
    category: '城市遗址',
    material: ['石灰岩'],
    description: '奇琴伊察是玛雅文明最著名的城邦遗址之一，以其标志性的库库尔坎金字塔（埃尔卡斯蒂略）而闻名。金字塔的设计体现了玛雅人卓越的天文知识。',
    detailedAnalysis: '库库尔坎金字塔高30米，四面各有91级台阶，加上顶端的平台共365级——对应一年的天数。春分和秋分的日落时分，金字塔北侧台阶上会出现蛇形光影，仿佛羽蛇神库库尔坎从天而降，展现了玛雅天文计算的精妙。遗址中还包括美洲最大的古代球场（长168米）、千柱广场、天文台（蜗牛塔）和圣井（用于祭祀的天然石灰岩洞）。奇琴伊察的建筑融合了玛雅和托尔特克两种文化风格，是玛雅-托尔特克文明融合的见证。',
    significance: '玛雅文明最具代表性的城邦遗址，展现了玛雅人与天文、数学融合的建筑艺术',
    themes: ['玛雅文明', '天文', '金字塔', '羽蛇神'],
    famousQuotes: ['"玛雅人将天文学写在了石头上"'],
    imageClass: 'artifact-pyramid',
    icon: '🗿',
    tags: ['墨西哥', '玛雅', '金字塔', '天文', '1840年'],
    featured: false,
    pageUrl: 'pages/americas_civilization.html',
    excavationStatus: '部分发掘和修复完成',
    currentLocation: '墨西哥尤卡坦州奇琴伊察考古遗址',
    conservationStatus: 'good',
    impactLevel: 4
  },
  {
    id: 'hammurabi_code',
    name: '汉谟拉比法典',
    nameEn: 'Code of Hammurabi',
    location: '伊朗苏萨（发现地）',
    country: '伊拉克（原产地）',
    region: 'mesopotamia',
    year: 1901,
    era: '古巴比伦时期',
    eraYear: '约公元前1754年',
    discoverer: '古斯塔夫·热基耶 (法属波斯考古队)',
    category: '石碑',
    material: ['玄武岩'],
    description: '汉谟拉比法典石碑是世界上最古老的法律文献之一，高2.25米。石碑顶部浮雕描绘了巴比伦国王汉谟拉比从太阳神沙马什手中接受法律的场景，下方用阿卡德楔形文字刻有282条法典条文。',
    detailedAnalysis: '汉谟拉比法典涵盖了刑法、民法、商法、婚姻法等多个领域，以"以眼还眼"（同态复仇）原则著称，但实际内容远比这个概括复杂。法典对不同社会阶层（自由人、半自由人、奴隶）规定了不同的惩罚标准。法典的序言和后记宣称其目的是"使正义遍及大地，消灭邪恶与恶人，使强者不欺凌弱者"。石碑原本竖立在巴比伦的西帕尔城，公元前12世纪被埃兰人作为战利品运至苏萨。其发现彻底改变了人们对古巴比伦社会和美索不达米亚法律体系的认识。',
    significance: '现存最古老的成文法典之一，奠定了美索不达米亚法律研究的基础',
    themes: ['法律', '巴比伦', '楔形文字', '石碑'],
    famousQuotes: ['"以眼还眼，以牙还牙" — 汉谟拉比法典第196条'],
    imageClass: 'artifact-law',
    icon: '⚖️',
    tags: ['伊拉克', '巴比伦', '法律', '楔形文字', '1901年'],
    featured: false,
    pageUrl: 'pages/mesopotamia.html',
    excavationStatus: '已完整保存',
    currentLocation: '法国巴黎卢浮宫',
    conservationStatus: 'excellent',
    impactLevel: 5
  },
  {
    id: 'angkor_wat',
    name: '吴哥窟',
    nameEn: 'Angkor Wat',
    location: '柬埔寨暹粒省',
    country: '柬埔寨',
    region: 'china',
    year: 1860,
    era: '高棉帝国时期',
    eraYear: '约公元1113-1150年',
    discoverer: '亨利·穆奥 (Henri Mouhot，向西方世界介绍)',
    category: '宗教建筑',
    material: ['砂岩'],
    description: '吴哥窟是世界上最大的宗教建筑群，占地约162.6公顷。由高棉国王苏利耶跋摩二世修建，最初供奉印度教毗湿奴神，后转变为佛教寺庙。2013年激光雷达扫描揭示了庞大的城市基础设施。',
    detailedAnalysis: '吴哥窟中央塔高65米，整个建筑群被一条190米宽的护城河包围。寺庙的墙壁上雕刻着总长约800米的精美浮雕，描绘了印度史诗《摩诃婆罗多》和《罗摩衍那》的故事场景、高棉军队出征、天堂地狱图景等。激光雷达（LiDAR）测绘技术的应用彻底改变了人们对吴哥的认识——在丛林中隐藏着庞大的道路、运河和水池网络，证明吴哥曾是世界上最大的前工业城市之一，鼎盛时期面积超过1000平方公里，人口可能达到百万。吴哥文明的衰落可能与气候变化导致的水利系统崩溃有关。',
    significance: '世界上最大的宗教建筑群，高棉帝国的辉煌见证',
    themes: ['高棉', '印度教', '佛教', '建筑'],
    famousQuotes: ['"吴哥是石头织就的诗篇"'],
    imageClass: 'artifact-temple',
    icon: '🛕',
    tags: ['柬埔寨', '高棉', '寺庙', '印度教', '1860年'],
    featured: false,
    pageUrl: 'pages/chinese_archaeology.html',
    excavationStatus: '持续修复和研究中',
    currentLocation: '柬埔寨暹粒吴哥考古公园',
    conservationStatus: 'fair',
    impactLevel: 4
  },
  {
    id: 'easter_island',
    name: '复活节岛摩艾石像',
    nameEn: 'Easter Island Moai',
    location: '智利复活节岛（拉帕努伊）',
    country: '智利',
    region: 'americas',
    year: 1722,
    era: '拉帕努伊文化时期',
    eraYear: '约公元1250-1500年',
    discoverer: '雅各布·罗赫芬 (欧洲首次记录)',
    category: '石像',
    material: ['凝灰岩', '火山岩'],
    description: '复活节岛上分布着约900尊巨型摩艾石像，最高的达10米、重82吨。这些石像由拉帕努伊人用火山凝灰岩雕刻而成，如何运输和竖立至今仍是一个令人着迷的谜题。',
    detailedAnalysis: '摩艾石像绝大多数在拉诺拉拉库火山采石场雕刻完成，然后被运送到岛屿各处的阿胡（石质平台上）。传统观点认为运输需要大量木材作为滚轴，导致了岛上森林的砍伐和生态崩溃。但近年来的实验考古学证明，石像可以通过左右摇摆"走"到目的地。许多摩艾曾被人推倒，现代考古学家对其中约50尊进行了重新竖起。大多数摩艾面向内陆（守望族人），而非面对海洋。2023年的新发现揭示了摩艾石像下方还有埋藏的身体部分，其上刻有复杂的岩画图案。',
    significance: '太平洋岛屿文明最壮观的遗迹，展现了人类在极端环境中的创造力',
    themes: ['太平洋', '石像', '岛屿', '生态'],
    famousQuotes: ['"他们用石头雕刻了祖先的灵魂"'],
    imageClass: 'artifact-moai',
    icon: '🗿',
    tags: ['智利', '复活节岛', '石像', '拉帕努伊', '1722年'],
    featured: false,
    pageUrl: 'pages/americas_civilization.html',
    excavationStatus: '部分修复和研究持续中',
    currentLocation: '智利复活节岛拉帕努伊国家公园',
    conservationStatus: 'fair',
    impactLevel: 4
  },
  {
    id: 'vix_burial',
    name: '维克斯公主墓',
    nameEn: 'Vix Grave',
    location: '法国勃艮第',
    country: '法国',
    region: 'greek-roman',
    year: 1953,
    era: '铁器时代哈尔施塔特文化',
    eraYear: '约公元前500年',
    discoverer: '莫里斯·莫瓦松和雷内·若弗鲁瓦',
    category: '墓葬',
    material: ['青铜', '金', '琥珀', '陶'],
    description: '维克斯公主墓是铁器时代欧洲最富有的墓葬之一。墓中出土的维克斯青铜酒器高1.64米、重208公斤，是古代世界已知最大的青铜容器之一，显示了凯尔特贵族与希腊世界广泛的贸易联系。',
    detailedAnalysis: '墓主是一位约30-35岁的女性，显然地位极高。随葬品中最震撼的是巨大的维克斯青铜巨爵——这个希腊风格的酒器可以盛装1100升葡萄酒，说明凯尔特精英阶层对地中海奢侈品的喜好和消费能力。此外还出土了金项圈（重480克，纯度接近24K）、伊特鲁里亚青铜壶、阿提卡黑陶杯、琥珀项链和四轮马车残件。该墓葬的发现彻底改变了人们对铁器时代欧洲"野蛮人"的刻板印象，揭示了横跨大陆的贸易和文化交流网络。',
    significance: '证明铁器时代欧洲精英与地中海世界存在大规模贸易的杰出墓葬',
    themes: ['铁器时代', '凯尔特', '贸易', '女性'],
    famousQuotes: ['"这不是野蛮人的墓葬，而是一位女王的安息之所"'],
    imageClass: 'artifact-vessel',
    icon: '🏺',
    tags: ['法国', '铁器时代', '凯尔特', '青铜器', '1953年'],
    featured: false,
    pageUrl: 'pages/greek_roman.html',
    excavationStatus: '已完成发掘',
    currentLocation: '法国沙蒂永-苏尔-塞纳考古博物馆',
    conservationStatus: 'excellent',
    impactLevel: 3
  },
  {
    id: 'olduvai_gorge',
    name: '奥杜威峡谷',
    nameEn: 'Olduvai Gorge',
    location: '坦桑尼亚北部塞伦盖蒂平原',
    country: '坦桑尼亚',
    region: 'egypt',
    year: 1931,
    era: '早更新世',
    eraYear: '约200万-15000年前',
    discoverer: '路易斯·利基和玛丽·利基',
    category: '古人类遗址',
    material: ['化石'],
    description: '奥杜威峡谷是古人类学最重要的遗址之一，被誉为"人类的摇篮"。玛丽和路易斯·利基夫妇在此发现了大量早期人类化石和石器工具，将人类起源研究推向了新纪元。',
    detailedAnalysis: '奥杜威峡谷是一个深约90米的峡谷，暴露出从200万年前到15000年前的连续地层。1959年，玛丽·利基发现了"鲍氏东非人"（Paranthropus boisei）头骨化石（被称为"胡桃夹子人"，因其巨大的臼齿），年代约175万年。随后，路易斯·利基在此发现了能人（Homo habilis）化石——这是迄今已知最早的人属成员之一。遗址还出土了大量奥杜威石器工具（Oldowan tools），是已知最古老的石器技术，标志着人类技术行为的起源。利基家族的工作培养了一代又一代的古人类学家，奠定了东非作为人类起源核心区域的地位。',
    significance: '20世纪最重要的古人类遗址之一，人类起源研究的里程碑',
    themes: ['古人类', '石器', '人类起源', '坦桑尼亚'],
    famousQuotes: ['"我们是非洲的孩子" — 路易斯·利基'],
    imageClass: 'artifact-fossil',
    icon: '🦴',
    tags: ['坦桑尼亚', '古人类', '化石', '石器', '1931年'],
    featured: false,
    pageUrl: 'pages/excavation_sites.html',
    excavationStatus: '持续研究中',
    currentLocation: '坦桑尼亚奥杜威峡谷（原位）',
    conservationStatus: 'fair',
    impactLevel: 5
  },
  {
    id: 'altamira',
    name: '阿尔塔米拉洞穴壁画',
    nameEn: 'Altamira Cave Paintings',
    location: '西班牙坎塔布里亚',
    country: '西班牙',
    region: 'greek-roman',
    year: 1879,
    era: '旧石器时代晚期',
    eraYear: '约公元前36000-13000年',
    discoverer: '马塞利诺·桑斯·德·索图奥拉和他8岁的女儿玛丽亚',
    category: '洞穴壁画',
    material: ['矿物颜料', '木炭'],
    description: '阿尔塔米拉洞穴被认为是旧石器时代艺术的"西斯廷教堂"。1879年，一位8岁女孩在跟随父亲探索洞穴时抬头看到了洞顶上壮观的野牛壁画——这一发现最初被学术界质疑为伪造，直到20世纪初才得到承认。',
    detailedAnalysis: '阿尔塔米拉洞穴长约270米，壁画集中在入口附近的"彩绘大厅"。洞顶上画有约25幅栩栩如生的野牛、马、鹿和野猪等动物形象，使用赭石红、黑色和紫色等矿物颜料。艺术家巧妙地利用了洞顶岩石的自然凸起来赋予动物三维立体感。碳十四测年表明这些壁画创作于约36000-13000年前。洞穴的发现彻底改变了人们对史前人类智识和艺术能力的认知。由于游客呼出的二氧化碳导致壁画出现霉菌侵害，洞穴于2002年完全对公众关闭，但在附近建造了精美的复制洞穴供参观。',
    significance: '旧石器时代艺术的巅峰之作，改变了人们对史前人类能力的认知',
    themes: ['旧石器', '洞穴艺术', '壁画', '人类起源'],
    famousQuotes: ['"爸爸，看！牛！" — 玛丽亚·索图奥拉（8岁发现者）'],
    imageClass: 'artifact-cave',
    icon: '🎨',
    tags: ['西班牙', '旧石器', '洞穴', '壁画', '1879年'],
    featured: false,
    pageUrl: 'pages/greek_roman.html',
    excavationStatus: '保护性关闭中',
    currentLocation: '西班牙坎塔布里亚阿尔塔米拉洞穴（原位）',
    conservationStatus: 'poor',
    impactLevel: 5
  },
  {
    id: 'petra',
    name: '佩特拉古城',
    nameEn: 'Petra',
    location: '约旦马安省',
    country: '约旦',
    region: 'greek-roman',
    year: 1812,
    era: '纳巴泰王国时期',
    eraYear: '约公元前400年-公元106年',
    discoverer: '约翰·路德维希·伯克哈特 (西方重新发现)',
    category: '城市遗址',
    material: ['砂岩'],
    description: '佩特拉是纳巴泰人在玫瑰红色砂岩峭壁上雕刻出的壮丽城市。1812年瑞士探险家伯克哈特伪装成阿拉伯人重新发现了这座被西方遗忘的古城。其最著名的建筑"卡兹尼神殿"（宝库）高40米，完全从整块岩石中雕刻而出。',
    detailedAnalysis: '佩特拉位于阿拉伯沙漠和地中海之间的战略位置，是古代香料贸易路线上最重要的中转站。纳巴泰人通过控制贸易积累了巨额财富，在约264平方公里的区域内建造了约800座石刻建筑。除了标志性的卡兹尼神殿（因《印第安纳琼斯》电影而闻名全球），还有容纳4000人的罗马式剧场、皇家墓葬群、修道院（代尔）和精密的水利系统（包括水坝、渠道和水池，能在沙漠中为3万人供水）。佩特拉在公元363年和747年经历大地震后逐渐衰落，被西方遗忘。',
    significance: '纳巴泰文明的杰出代表，岩石建筑史上的奇迹',
    themes: ['纳巴泰', '石刻', '贸易', '沙漠'],
    famousQuotes: ['"玫瑰红城市，时间的一半年纪" — 约翰·威廉·伯根'],
    imageClass: 'artifact-petra',
    icon: '🕌',
    tags: ['约旦', '纳巴泰', '石刻', '沙漠', '1812年'],
    featured: false,
    pageUrl: 'pages/excavation_sites.html',
    excavationStatus: '大部分已发掘',
    currentLocation: '约旦佩特拉考古公园',
    conservationStatus: 'fair',
    impactLevel: 4
  },
  {
    id: 'ur_royal_tombs',
    name: '乌尔王陵',
    nameEn: 'Royal Tombs of Ur',
    location: '伊拉克济加尔省乌尔',
    country: '伊拉克',
    region: 'mesopotamia',
    year: 1922,
    era: '苏美尔早王朝时期',
    eraYear: '约公元前2600年',
    discoverer: '伦纳德·伍利 (Leonard Woolley)',
    category: '陵墓',
    material: ['金', '银', '青金石', '红玉髓', '贝壳'],
    description: '乌尔王陵是苏美尔文明最壮观的考古发现之一。伍利发掘了16座王室墓葬，其中普阿比女王（Puabi）的陵墓保存完好，出土了令人叹为观止的黄金头饰、珠宝、竖琴和游戏棋盘。',
    detailedAnalysis: '乌尔王陵的发现震惊了当时的世界——其丰富的随葬品几乎可以与图坦卡蒙墓媲美。普阿比女王的头饰由金叶、金环链和青金石珠精心编织而成；"灌木丛中的公羊"雕像（高45.7厘米）由金、银、青金石、贝壳和红石灰岩制成，是苏美尔艺术的巅峰之作；牛头竖琴以金箔包裹的牛头装饰音箱，显示了苏美尔音乐文化的高度发达。最令人惊骇的发现是"大死亡坑"——在几个王室墓穴入口处发现了大量殉葬者的遗骸，包括士兵、侍女和乐师，表明苏美尔存在人殉制度。伍利对这些墓葬的发掘（1922-1934年）被认为是美索不达米亚考古黄金时代的标志。',
    significance: '苏美尔文明最壮观的王室墓葬，揭示了人类最早的文明之一的高度成就',
    themes: ['苏美尔', '王室', '黄金', '墓葬'],
    famousQuotes: ['"乌尔的王陵令法老也黯然失色"'],
    imageClass: 'artifact-tomb',
    icon: '👸',
    tags: ['伊拉克', '苏美尔', '王陵', '黄金', '1922年'],
    featured: false,
    pageUrl: 'pages/mesopotamia.html',
    excavationStatus: '已完成发掘',
    currentLocation: '英国伦敦大英博物馆 / 美国宾夕法尼亚大学博物馆',
    conservationStatus: 'excellent',
    impactLevel: 5
  },
  {
    id: 'palace_knossos',
    name: '克诺索斯王宫',
    nameEn: 'Palace of Knossos',
    location: '希腊克里特岛伊拉克利翁',
    country: '希腊',
    region: 'greek-roman',
    year: 1900,
    era: '米诺斯文明',
    eraYear: '约公元前1900-1350年',
    discoverer: '亚瑟·埃文斯 (Arthur Evans)',
    category: '宫殿遗址',
    material: ['石', '木材', '壁画'],
    description: '克诺索斯是米诺斯文明最大的宫殿遗址，与希腊神话中的迷宫和米诺陶洛斯传说紧密相连。亚瑟·埃文斯爵士的发掘将欧洲文明的起源向前推进了千年。',
    detailedAnalysis: '克诺索斯宫殿占地约2万平方米，包含约1300个房间，环绕一个大型中央庭院而建。宫殿拥有先进的设施：复杂的排水系统、冲水厕所、多层建筑和精美的壁画（如"跳牛图"、"巴黎女郎"和"百合王子"）。埃文斯的部分修复工作（尤其是使用钢筋混凝土）在现代考古学中备受争议，但他的贡献不可否认——他发现了三种不同阶段的文字（克里特象形文字、线形文字A和线形文字B），其中线形文字B在1952年被迈克尔·文特里斯破译为古希腊语的早期形式，这一发现彻底改变了希腊史前史。关于宫殿的最终毁灭，主流假说指向约公元前1450年圣托里尼火山爆发及其引发的海啸。',
    significance: '欧洲最古老文明——米诺斯文明的中心，将欧洲信史前推千年',
    themes: ['米诺斯', '青铜时代', '宫殿', '希腊神话'],
    famousQuotes: ['"我们发现了欧洲的第一个文明" — 亚瑟·埃文斯'],
    imageClass: 'artifact-palace',
    icon: '🏛️',
    tags: ['希腊', '米诺斯', '青铜时代', '宫殿', '1900年'],
    featured: false,
    pageUrl: 'pages/greek_roman.html',
    excavationStatus: '部分重建和修复',
    currentLocation: '希腊克里特克诺索斯考古遗址',
    conservationStatus: 'fair',
    impactLevel: 5
  }
];

// ==================== Archaeologists Database ====================
const ARCHAEOLOGISTS_DATABASE = [
  {
    id: 'howard_carter',
    name: '霍华德·卡特',
    nameEn: 'Howard Carter',
    nationality: '英国',
    years: '1874-1939',
    speciality: '埃及学',
    discovery: '图坦卡蒙陵墓 (1922)',
    description: '英国考古学家和埃及学家。经过多年在帝王谷的系统搜索，最终发现了几乎未被盗掘的图坦卡蒙墓。他的系统记录方法和文物保护理念影响了后来几代考古学家。',
    icon: '👨‍🔬'
  },
  {
    id: 'mary_leakey',
    name: '玛丽·利基',
    nameEn: 'Mary Leakey',
    nationality: '英国',
    years: '1913-1996',
    speciality: '古人类学',
    discovery: '奥杜威峡谷人类化石、莱托里脚印',
    description: '20世纪最伟大的古人类学家之一。在坦桑尼亚奥杜威峡谷发现了能人化石和大量早期石器，在莱托里发现了360万年前的人类脚印化石，对理解人类起源做出了不可磨灭的贡献。',
    icon: '👩‍🔬'
  },
  {
    id: 'heinrich_schliemann',
    name: '海因里希·施里曼',
    nameEn: 'Heinrich Schliemann',
    nationality: '德国',
    years: '1822-1890',
    speciality: '青铜时代考古',
    discovery: '特洛伊古城 (1870)、迈锡尼 (1876)',
    description: '德国商人和自学成才的考古学家。凭着对荷马史诗的信念，成功发现了特洛伊遗址和迈锡尼文明，开创了用考古证据验证文献传说的研究范式。其发掘方法虽有争议，但发现本身具有划时代意义。',
    icon: '👨‍💼'
  },
  {
    id: 'pei_wenzhong',
    name: '裴文中',
    nameEn: 'Pei Wenzhong',
    nationality: '中国',
    years: '1904-1982',
    speciality: '史前考古学',
    discovery: '北京猿人头盖骨 (1929)',
    description: '中国史前考古学奠基人之一。1929年在周口店发现了第一个完整的北京猿人头盖骨化石，将人类在中国的历史推至约50万年前。此外还主持了山顶洞人遗址和广西巨猿化石的发掘。',
    icon: '👨‍🏫'
  },
  {
    id: 'champollion',
    name: '商博良',
    nameEn: 'Jean-François Champollion',
    nationality: '法国',
    years: '1790-1832',
    speciality: '埃及学、语言学',
    discovery: '破译古埃及象形文字 (1822)',
    description: '法国语言学家和埃及学之父。通过对比罗塞塔石碑上的三种文字，成功破译了古埃及象形文字，为数千年的埃及历史打开了大门。他的突破性发现使埃及学成为一门真正的科学。',
    icon: '👨‍🏫'
  },
  {
    id: 'arthur_evans',
    name: '亚瑟·埃文斯',
    nameEn: 'Arthur Evans',
    nationality: '英国',
    years: '1851-1941',
    speciality: '爱琴海考古',
    discovery: '克诺索斯王宫 (1900)',
    description: '英国考古学家。在克里特岛发掘克诺索斯宫殿，发现了米诺斯文明——欧洲最古老的文明。他的发掘和修复工作使得这个被遗忘的青铜文明重见天日。',
    icon: '👨‍🔬'
  },
  {
    id: 'li_ji',
    name: '李济',
    nameEn: 'Li Ji',
    nationality: '中国',
    years: '1896-1979',
    speciality: '中国考古学',
    discovery: '殷墟发掘、西阴村遗址',
    description: '中国第一位受过西方训练的考古学家，被誉为"中国考古学之父"。主持了殷墟的早期发掘，是中国科学考古的开拓者。',
    icon: '👨‍🏫'
  },
  {
    id: 'klaus_schmidt',
    name: '克劳斯·施密特',
    nameEn: 'Klaus Schmidt',
    nationality: '德国',
    years: '1953-2014',
    speciality: '史前考古学',
    discovery: '哥贝克力石阵 (1994年起主持发掘)',
    description: '德国考古学家。在土耳其东南部发掘哥贝克力石阵，发现了人类已知最古老的大型仪式建筑群，彻底颠覆了关于文明起源的传统理论。',
    icon: '👨‍🔬'
  }
];

// ==================== Famous Quotes ====================
const ARCHAEOLOGY_QUOTES = [
  { text: '考古学使人谦卑。面对千年的尘埃，我们不过是时间长河中的一粒沙。', author: '莫蒂默·惠勒' },
  { text: '我们挖掘的不是过去，而是我们对自己的认知。', author: '玛格丽特·米德' },
  { text: '每一件文物都承载着一个时代的故事，等待着被倾听。', author: '佚名' },
  { text: '历史不会重复，但它会押韵。', author: '马克·吐温（常被考古学家引用）' },
  { text: '考古学是将散落在大地上的历史碎片重新拼接成完整图景的艺术。', author: '戈登·柴尔德' },
  { text: '那些不记得过去的人，注定要重复它。', author: '乔治·桑塔亚纳' },
  { text: '在考古学家眼中，每一寸土地都可能是一个故事的开端。', author: '保罗·巴恩' },
  { text: '文物不是死物，它们是跨越时间的信使。', author: '考古格言' },
  { text: '揭示过去是为了更好地理解现在，也是为了给未来留下线索。', author: '科林·伦弗鲁' },
  { text: '从前的日光很慢，在一件陶器上可以花上一整天。', author: '改编' },
  { text: '考古学是历史学最忠实的仆人，也是最有想象力的侦探。', author: '莫蒂默·惠勒' },
  { text: '文明的密码就藏在那些被岁月掩埋的瓦砾之中。', author: '佚名' }
];

// ==================== Helpers ====================
function getDiscoveryOfDay() {
  const now = new Date();
  const dayOfYear = Math.floor((now - new Date(now.getFullYear(), 0, 0)) / (1000 * 60 * 60 * 24));
  return DISCOVERY_DATABASE[dayOfYear % DISCOVERY_DATABASE.length];
}

function getDiscoveriesByRegion(region) {
  if (region === 'all') return DISCOVERY_DATABASE;
  return DISCOVERY_DATABASE.filter(d => d.region === region);
}

function getFeaturedDiscoveries(count = 9) {
  const featured = DISCOVERY_DATABASE.filter(d => d.featured);
  if (featured.length >= count) return featured.slice(0, count);
  return [...featured, ...DISCOVERY_DATABASE.filter(d => !d.featured)].slice(0, count);
}

function searchDiscoveries(query) {
  const q = query.toLowerCase();
  return DISCOVERY_DATABASE.filter(d =>
    d.name.includes(q) || d.nameEn.toLowerCase().includes(q) ||
    d.location.includes(q) || d.country.includes(q) ||
    d.description.includes(q) || d.era.includes(q) ||
    d.tags.some(t => t.includes(q)) || d.themes.some(t => t.includes(q)) ||
    (d.discoverer && d.discoverer.toLowerCase().includes(q))
  );
}

function getDiscoveryById(id) {
  return DISCOVERY_DATABASE.find(d => d.id === id);
}

// Export Globally
window.DISCOVERY_DATABASE = DISCOVERY_DATABASE;
window.ARCHAEOLOGISTS_DATABASE = ARCHAEOLOGISTS_DATABASE;
window.ARCHAEOLOGY_QUOTES = ARCHAEOLOGY_QUOTES;
window.getDiscoveryOfDay = getDiscoveryOfDay;
window.getDiscoveriesByRegion = getDiscoveriesByRegion;
window.getFeaturedDiscoveries = getFeaturedDiscoveries;
window.searchDiscoveries = searchDiscoveries;
window.getDiscoveryById = getDiscoveryById;